#!/usr/bin/env python3
"""Embed version, checklist, pitfall and conclusion material in its mechanism.

The first fusion pass collected recurring source tails at article level. That
made provenance disappear, but it also separated version boundaries and
diagnostic advice from the mechanism they qualify. This post-pass restores the
editorial relationship without restoring source-article wrappers.

Dry-run by default. A single-source tail is attributed from the original Git
source; a multi-source tail is attributed by the contextual H3 generated by
``editorial_fusion_rewrite.py``.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from editorial_fusion_rewrite import (
    FENCE_RE,
    HEADING_RE,
    classify_tail,
    normalize_heading,
    shift_headings,
    split_frontmatter,
    trim_blank,
)


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "metadata/2026-08-24-editorial-fusion-v3.json"
MAP_PATH = ROOT / "metadata/2026-08-24-content-consolidation-v2-map.json"
CATEGORY_TITLES = {
    "versions": "版本与实现边界",
    "checklists": "诊断与验证清单",
    "pitfalls": "常见误区",
    "conclusions": "结论",
}


@dataclass
class H2Block:
    title: str
    lines: list[str]


def headings(lines: list[str], level: int) -> list[tuple[int, str]]:
    result: list[tuple[int, str]] = []
    fenced = False
    for index, line in enumerate(lines):
        if FENCE_RE.match(line):
            fenced = not fenced
            continue
        match = HEADING_RE.match(line) if not fenced else None
        if match and len(match.group(1)) == level:
            result.append((index, match.group(3)))
    return result


def split_article(body: str) -> tuple[list[str], list[H2Block]]:
    lines = body.splitlines()
    positions = headings(lines, 2)
    if not positions:
        return lines, []
    prefix = lines[: positions[0][0]]
    blocks: list[H2Block] = []
    for index, (start, title) in enumerate(positions):
        end = positions[index + 1][0] if index + 1 < len(positions) else len(lines)
        blocks.append(H2Block(title, trim_blank(lines[start + 1 : end])))
    return trim_blank(prefix), blocks


def source_text(path: str) -> str:
    run = subprocess.run(
        ["git", "show", f"HEAD:{path}"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return run.stdout


def source_title_and_tails(text: str) -> tuple[str, list[tuple[str, str]]]:
    _, body = split_frontmatter(text)
    lines = body.splitlines()
    h1s = headings(lines, 1)
    if len(h1s) != 1:
        raise ValueError(f"expected one source H1, got {len(h1s)}")
    tails = []
    for _, title in headings(lines, 2):
        category = classify_tail(title)
        if category in CATEGORY_TITLES:
            tails.append((category, title))
    return h1s[0][1], tails


def original_tail_owners(
    specs: dict[str, dict[str, object]],
) -> dict[tuple[str, str], tuple[str, str]]:
    path_map = json.loads(MAP_PATH.read_text(encoding="utf-8"))
    sources: defaultdict[str, list[str]] = defaultdict(list)
    for row in path_map["paths"]:
        if row["disposition"] == "merged":
            sources[str(row["target_path"])].append(str(row["source_path"]))

    result: dict[tuple[str, str], tuple[str, str]] = {}
    for target, spec in specs.items():
        title_map = {
            str(section["from"]): str(section["title"])
            for section in spec["sections"]
        }
        found: defaultdict[str, list[tuple[str, str]]] = defaultdict(list)
        for source in sources.get(target, []):
            old_title, tails = source_title_and_tails(source_text(source))
            new_title = title_map.get(old_title)
            if not new_title:
                continue
            for category, tail_title in tails:
                found[category].append((new_title, tail_title))
        for category, rows in found.items():
            if len(rows) == 1:
                result[(target, category)] = rows[0]
    return result


def split_h3(lines: list[str]) -> tuple[list[str], list[tuple[str, list[str]]]]:
    positions = headings(lines, 3)
    if not positions:
        return trim_blank(lines), []
    prefix = trim_blank(lines[: positions[0][0]])
    groups = []
    for index, (start, title) in enumerate(positions):
        end = positions[index + 1][0] if index + 1 < len(positions) else len(lines)
        groups.append((title, trim_blank(lines[start + 1 : end])))
    return prefix, groups


def clean_section_title(value: str, fallback: str) -> str:
    value = re.sub(r"^(?:\d+(?:\.\d+)*|[一二三四五六七八九十]+)[.、：:]\s*", "", value).strip()
    normalized = normalize_heading(value)
    generic = {
        normalize_heading("版本边界"),
        normalize_heading("版本与实现边界"),
        normalize_heading("常见误区"),
        normalize_heading("相关误区"),
        normalize_heading("诊断与验证清单"),
        normalize_heading("检查项"),
        normalize_heading("结论"),
    }
    return fallback if not value or normalized in generic else value


def append_section(block: H2Block, title: str, content: list[str]) -> None:
    block.lines = trim_blank(block.lines)
    if block.lines:
        block.lines.append("")
    block.lines.extend([f"### {title}", ""])
    block.lines.extend(trim_blank(content))


def embed_text(
    original: str,
    target: str,
    spec: dict[str, object],
    owners: dict[tuple[str, str], tuple[str, str]],
) -> tuple[str, list[str]]:
    frontmatter, body = split_frontmatter(original)
    prefix, blocks = split_article(body)
    by_title = {block.title: block for block in blocks}
    mechanism_titles = [str(section["title"]) for section in spec["sections"]]
    changes: list[str] = []
    retained: list[H2Block] = []

    for block in blocks:
        category = next(
            (key for key, title in CATEGORY_TITLES.items() if block.title == title),
            None,
        )
        if not category:
            retained.append(block)
            continue

        fallback = CATEGORY_TITLES[category]
        prefix_lines, groups = split_h3(block.lines)
        leftovers: list[tuple[str, list[str]]] = []
        moved = 0

        if groups:
            for context, content in groups:
                owner = next(
                    (
                        title
                        for title in mechanism_titles
                        if context.startswith(f"{title}：") and title in by_title
                    ),
                    None,
                )
                if not owner:
                    leftovers.append((context, content))
                    continue
                detail = context[len(owner) + 1 :]
                section_title = clean_section_title(detail, fallback)
                append_section(by_title[owner], section_title, content)
                changes.append(f"{block.title} -> {owner} / {section_title}")
                moved += 1
        elif (target, category) in owners:
            owner, original_title = owners[(target, category)]
            if owner in by_title:
                restored = shift_headings(block.lines, 1)
                section_title = clean_section_title(original_title, fallback)
                append_section(by_title[owner], section_title, restored)
                changes.append(f"{block.title} -> {owner} / {section_title}")
                moved += 1
                prefix_lines = []

        if not moved:
            retained.append(block)
            continue

        leftover_lines = trim_blank(prefix_lines)
        for context, content in leftovers:
            if leftover_lines:
                leftover_lines.append("")
            leftover_lines.extend([f"### {context}", ""])
            leftover_lines.extend(content)
        if leftover_lines:
            retained.append(H2Block(block.title, trim_blank(leftover_lines)))

    output = trim_blank(prefix)
    for block in retained:
        if output:
            output.append("")
        output.extend([f"## {block.title}", ""])
        output.extend(trim_blank(block.lines))
    revised = f"---\n{frontmatter}\n---\n\n" + "\n".join(output).rstrip() + "\n"
    return revised, changes


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--target")
    args = parser.parse_args()

    data = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    specs = data["targets"]
    owners = original_tail_owners(specs)
    changed_files = 0
    moved_sections = 0
    for target, spec in specs.items():
        if args.target and target != args.target:
            continue
        path = ROOT / target
        if not path.exists():
            continue
        revised, changes = embed_text(
            path.read_text(encoding="utf-8"), target, spec, owners
        )
        if not changes:
            continue
        changed_files += 1
        moved_sections += len(changes)
        print(target)
        for change in changes:
            print(f"  {change}")
        if args.apply:
            path.write_text(revised, encoding="utf-8")
    mode = "applied" if args.apply else "dry-run"
    print(f"{mode}: embedded {moved_sections} sections across {changed_files} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
